homePage: home
redirects:
  some-old-page:
    newPage: some-new-page
    code: 301
  en:
    newPage: en/home
router:
tableOfContents:
  - page: en/introduction
    icon: fas fa-home
    children:
      - page: en/introduction/what-is-hubleto
      - page: en/introduction/who-is-hubleto-for
      - page: en/introduction/how-to-use-this-guide
  - page: en/getting-started
    icon: fas fa-play
    children:
      - page: en/getting-started/registration-and-login
      - page: en/getting-started/homepage-overview
      - page: en/getting-started/menu-navigation
  - page: en/features-overview
    icon: fas fa-star
    children:
      - page: en/features-overview/ai-assistant
      - page: en/features-overview/global-search
      - page: en/features-overview/app-layout-data-grids
      - page: en/features-overview/record-form-layout
  - page: en/apps
    icon: fas fa-book
    children:
      - page: en/apps/crm
        children:
          - page: en/apps/crm/customers
          - page: en/apps/crm/contacts
          - page: en/apps/crm/calendar
          - page: en/apps/crm/documents
          - page: en/apps/crm/workflow
          - page: en/apps/crm/mail
          - page: en/apps/crm/tasks
          - page: en/apps/crm/dashboards
      - page: en/apps/marketing
        children:
          - page: en/apps/marketing/campaigns
          - page: en/apps/marketing/leads
      - page: en/apps/sales
        children:
          - page: en/apps/sales/suppliers
          - page: en/apps/sales/deals
          - page: en/apps/sales/products
          - page: en/apps/sales/orders
      - page: en/apps/productivity
        children:
          - page: en/apps/productivity/tasks
          - page: en/apps/productivity/worksheets
          - page: en/apps/productivity/projects
          - page: en/apps/productivity/issues
      - page: en/apps/warehouses
        children:
          - page: en/apps/warehouses/warehouses
          - page: en/apps/warehouses/inventory
      - page: en/apps/finance
        children:
          - page: en/apps/finance/invoices
      - page: en/apps/communication
        children:
          - page: en/apps/communication/discussions
      - page: en/apps/maintenance
        children:
          - page: en/apps/maintenance/notifications
          - page: en/apps/maintenance/settings
          - page: en/apps/maintenance/tools
      - page: en/apps/help
        children:
          - page: en/apps/help/help
          - page: en/apps/help/about
